server {
    listen 80;

    location = / {
        return 301 /daily_self_care_tracker/;
    }

    location / {
        root   /usr/share/nginx/html;
        index  index.html;
        try_files $uri $uri/ /daily_self_care_tracker/index.html;
    }

    error_page 404 /daily_self_care_tracker/index.html;

    error_page 500 502 503 504 /50x.html;

    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
